### ISSUE TITLE
Wolverine.new(config) with custom script_path cannot be used on latest version 0.3.3

### ISSUE THREAD

**Issue by aeroastro** [Shopify/wolverine#19]
Hi. :cat:

Sorry, but could you release 0.3.4 to rubygems in order to apply #15?

On current 0.3.3, when `Wolverine.new(config)` is used with custom `config.script_path` instead of `app/wolverine`, `include_partial` helper in ERB template fails because it searches script in `app/wolverine` instead of specified `config.script_path`.

Although, I can specify `branch: :master` on Gemfile or change `Wolverine.config` on runtime to workaround this issue, it would be very helpful of you to release the new version to fix this bug.

https://rubygems.org/gems/wolverine/versions/

**Comment by burke** [comment]
Sure, I've just pushed 0.3.4
